language: java
jdk: oraclejdk8
sudo: true
services:
  - docker
before_install:
  - chmod +x mvnw
script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)
  - docker-compose build -e $(git rev-parse HEAD)
  - git log -5
notifications:
    slack: j-coll-art-service:6CMGMmkkSYGiK2nAZpxpLKfF
