language: java
jdk: oraclejdk8
sudo: true
services:
  - docker
python:
  - "3.4"
before_install:
  - chmod +x mvnw
addons:
  apt:
    sources:
      - deadsnakes 
    packages:
      - python3.4
script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)
#after_success:
  - echo "TAG=latest" > .env
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region us-east-1) 
  - docker-compose build
  - docker tag artservicesourcingdataservice:latest 257777415217.dkr.ecr.us-east-1.amazonaws.com/artservicesourcingdataservice:latest
  - docker push 257777415217.dkr.ecr.us-east-1.amazonaws.com/artservicesourcingdataservice:latest
  - rm .env
notifications:
    slack: j-coll-art-service:6CMGMmkkSYGiK2nAZpxpLKfF
